### ISSUE TITLE
Date/time format displayed on lock screen

### ISSUE THREAD

**Issue by Varrkan82** [bentezhniy/miui_10_ukrainian_public#16]
Date/time format displayed on lock screen instead a date/time itself.
First time appeared in Xiaomi.Eu v.21.2.24. Mi 9T Pro.
![IMG_20210226_214323](https://user-images.githubusercontent.com/7004992/109347790-5c9cf480-787c-11eb-906e-3b428519b40d.jpg)

**Comment by deivids84** [comment]
Sorry, fixed
