### ISSUE TITLE
Wrong translation

### ISSUE THREAD

**Issue by Varrkan82** [bentezhniy/miui_10_ukrainian_public#21]
![IMG_20210417_153652.jpg](https://user-images.githubusercontent.com/7004992/115113408-e458d280-9f92-11eb-88a5-5843ac0c26aa.jpg)
This should be translated as "Передача даних" or "Мобільний Інтернет"

**Comment by deivids84** [comment]
https://crowdin.com/translate/miui-xiaomieu-catalan/8084/en-uk#911032

**Comment by vim-x** [comment]
Fixed
