### ISSUE TITLE
Wrong size displayed in Cleaner app

### ISSUE THREAD

**Issue by Varrkan82** [bentezhniy/miui_10_ukrainian_public#23]
Wrong size displayed in Cleaner app. Ci instead Bytes or Kilobytes (don't know exactly what should be displayed there)
![IMG_20210810_225209.jpg](https://user-images.githubusercontent.com/7004992/128926493-71d4f46d-4a24-44ec-a128-0959b6a7ceef.jpg)

**Comment by vim-x** [comment]
Please check again. (Будь ласка провірте ще раз).

**Comment by Varrkan82** [comment]
> Please check try again. (Будь ласка провірте ще раз).

Нажаль на мою модель більше немає оновлень. Тому залишився з цим багом...

**Comment by vim-x** [comment]
> > Please check try again. (Будь ласка провірте ще раз).
> 
> Нажаль на мою модель більше немає оновлень. Тому залишився з цим багом...

Зрозуміло!
