### ISSUE TITLE
XML issues

### ISSUE THREAD

**Issue by ingbrzy** [bentezhniy/miui_10_ukrainian_public#8]
fix your XML issues https://translators.xiaomi.eu/XML_MIUI10-Ukrainian-uk.html

**Comment by bentezhniy** [comment]
I'll fix it today later

сб, 1 черв. 2019, 07:18 користувач ingbrzy <notifications@github.com> пише:

**Comment by bentezhniy** [comment]
All errors are fixed 3 hours ago 🙃

пт, 31 трав. 2019, 22:44 користувач ingbrzy <notifications@github.com> пише:

**Comment by ingbrzy** [comment]
Thanks
